### ISSUE TITLE
Installing the app

### ISSUE THREAD

**Issue by Mima2370** [Zaiqin/Billionaire-City#1]
Hi there!

I tried installing the app from the Play Store (https://play.google.com/store/apps/details?id=com.ZQStudios.BillionaireCity), but it's saying that all of my devices are incompatible (while that isn't the case, I believe). Is it possible to fix this somehow?

On the other hand, I'm really happy there's finally a project to revive Millionaire City. Have been looking for it since a while :)

**Comment by Zaiqin** [comment]
Hi, may I know what device you are using and the android version?

**Comment by Mima2370** [comment]
> Hi, may I know what device you are using and the android version?

Samsung Galaxy A51 with android 13

I live in Belgium, don't know if that might be a reason as well.

**Comment by Zaiqin** [comment]
Yup it is the country restriction, give Google Play some time to review the new update

**Comment by Mima2370** [comment]
Alright, thanks :)
